name: Update Weather

on:
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch:

jobs:
  update-weather:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Get weather
        run: |
          CITY="London"
          API_KEY="${{ secrets.OPENWEATHER_API_KEY }}"
          TEMP=$(curl -s "https://api.openweathermap.org/data/2.5/weather?q=$CITY&appid=$API_KEY&units=metric" | jq ".main.temp" | xargs printf "%.0f")
          DESC=$(curl -s "https://api.openweathermap.org/data/2.5/weather?q=$CITY&appid=$API_KEY&units=metric" | jq -r ".weather[0].main")
          echo "🌦 $CITY: ${TEMP}°C, $DESC" > weather.txt

      - name: Update README
        run: |
          awk '/<!-- WEATHER -->/ { system("cat weather.txt"); next }1' README.md > README_new.md
          mv README_new.md README.md

      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add README.md
          git commit -m "Updated weather" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main --force
