name: Update Weather

on:
  schedule:
    - cron: "0 */3 * * *"  # Runs every 3 hours
  workflow_dispatch:

jobs:
  update-weather:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false   # We'll use PAT for pushing

      # Step 2: Fetch current weather from OpenWeatherMap
      - name: Get weather
        run: |
          CITY="London"
          API_KEY="${{ secrets.OPENWEATHER_API_KEY }}"
          TEMP=$(curl -s "https://api.openweathermap.org/data/2.5/weather?q=$CITY&appid=$API_KEY&units=metric" | jq ".main.temp" | xargs printf "%.0f")
          DESC=$(curl -s "https://api.openweathermap.org/data/2.5/weather?q=$CITY&appid=$API_KEY&units=metric" | jq -r ".weather[0].main")
          echo "🌦 $CITY: ${TEMP}°C, $DESC" > weather.txt

      # Step 3: Update README at the placeholder <!-- WEATHER -->
      - name: Update README
        run: |
          awk '/<!-- WEATHER -->/ { system("cat weather.txt"); next }1' README.md > README_new.md
          mv README_new.md README.md

      # Step 4: Commit and push changes using PAT
      - name: Commit and Push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add README.md
          git commit -m "Updated weather" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }} HEAD:main
